### ISSUE TITLE
Architecture doc

### ISSUE THREAD

**Issue by erlend-sh** [fishfolks/punchy#201]
### Description

A living architecture.md doc would make it easier for newcomers to grok our project.

https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html

**Comment by 64kramsystem** [comment]
Just yesterday, I've put on paper the current state machine for enemy behavior. I was thinking of putting it on a wiki page (as a begin), but the SCM does it as well.

**Comment by zicklag** [comment]
I feel like a wiki page would be a good way to do it actually, because I'd bet that, at this stage of development especially, it will probably end up mildly out-of-date frequently and need some sprucing up, and it might make it easier for us to do that if changing it didn't require a PR.

At the same time, I've seen a lot of neglected wikis on GitHub, so let's just try not to forget that it's there. :)

**Comment by erlend-sh** [comment]
Maybe just a Discussion for starters then, like the Resources doc: https://github.com/fishfolks/punchy/discussions/150 (I will be coming back to it!)

**Comment by zicklag** [comment]
I feel like a wiki page probably makes sense for both. I feel a little weird editing somebody else's discussion, and it gives the impression that the one person wrote the whole thing.

How would you feel about moving the resources discussion to a wiki page?

If we made the wiki a home for developer resources and education material I think that would feel fitting.

Then user-facing stuff would probably go in a normal website later, and we would focus the wiki on developer-facing documentation.

**Comment by erlend-sh** [comment]
Sure, let’s give wiki a try 👍

**Comment by zicklag** [comment]
@64kramsystem there's a page [here](https://github.com/fishfolks/punchy/wiki/Architecture) that you could dump your architecture write-up you started.

**Comment by erlend-sh** [comment]
Closed by #214 which points to wiki page mentioned above. Discussion continues in #216
