### ISSUE TITLE
Solve commands flushing (1-frame-bug related) issues

### ISSUE THREAD

**Issue by odecay** [fishfolks/punchy#99]
EDIT: #203 was made to solve (more or less completely) this problem. Currently, the bug mentioned below is still present (still requires a workaround).

Currently, we have commands flushing issues (1-frame-lag related bugs), and likely race conditions.

Structuring commands flushes is something that IMO needs to be tackled ASAP, because the more time passes, the more (and more subtle) bugs will arise.

Currently the game has [one recognized bug](https://github.com/fishfight/punchy/blob/72c83a68b1e931f470b38c3513d6eeef80b86757/src/attack.rs#L363), which requires a workaround. I suspect that there are also race conditions.

Note that this is orthogonal to state design.

**Comment by 64kramsystem** [comment]
I totally agree with this proposal. :joy:

**Comment by zicklag** [comment]
Seems reasonable to me.

**Comment by 64kramsystem** [comment]
@zicklag @odecay Phew! :sweat_smile: let me know what you think.

**Comment by odecay** [comment]
My initial impressions are of this are very positive. I feel like what you have done in sorting through all the systems already to list them like this was a big task, and the way you have ordered them makes perfect sense to me.

I will think about this some more and see what other feedback I can suggest but I feel this is a good way to proceed.

**Comment by 64kramsystem** [comment]
> In regards to events, my understanding of what you are saying is that you find them helpful but there will be less need to rely on them in this architecture.

Yes, exactly. Event messaging, in this context, can serve two purposes:

1. to establish a temporal association - a reader implicitly acts _after_ a writer, and/or to establish a 1:1 association between systems (when there is only 1 publisher and 1 subscriber)
2. to model a single publisher/multiple subscribers model

Point 2 is what event messaging is exactly for, so they're an exact fit :smile: 

Regarding Point 1, with proper stages in place, if one wants to model temporal association, they won't need events (or labels) anymore, so they can model via components if they wish. Using events for 1:1 associations will be therefore a more cosmetic choice, which is of course a valid choice.  
We may decide to establish a guideline, so that we have a consistent usage; a decision to model 1:1 associations via event messaging (and later change an association to be components-based if it becomes 1:many) is perfectly valid.

**Comment by zicklag** [comment]
I haven't done a thorough review, but I think I'll leave that mostly to you guys so I keep my focus on the non-gameplay stuff I've been focusing on. :) And good job on the breakdown!

One point I will make is to keep in mind our ability to establish "this system runs after this system" relationships _without_ stages ( i.e `.after()` ), and that is something that I think Bevy has been leaning towards. The idea that you don't need to group all your systems into stages necessarily, but you can say that certain systems must run in a specific order, which can help increase the parallelism, because Bevy doesn't need to wait for _all_ systems in a given stage to finish before starting the next stage.

That doesn't mean we shouldn't use stages, it's just something to keep in mind. More stages will reduce how much bevy can parallelize, and sometimes when a new system doesn't really need to fit into any existing stage, you'll just add it to one in a way that seems somewhat arbitrary.

---

As for the `load_fighters` it should run after `load_level`, to make sure fighters are loaded as soon as possible without a frame lag, but it isn't really critical.

`update_canvas_size` just has to run before rendering.

I think `hot_reload_*` should run before almost everything, to make sure the assets are updated before the game starts to try and use them.

**Comment by 64kramsystem** [comment]
I've updated the design following the directions about the remaining systems.

> That doesn't mean we shouldn't use stages, it's just something to keep in mind. More stages will reduce how much bevy can parallelize, and sometimes when a new system doesn't really need to fit into any existing stage, you'll just add it to one in a way that seems somewhat arbitrary.

I think we'll need to see how the project evolves, as it may take different shapes. There may be an explosion of systems :grimacing: and setting some/many/any 1:1 temporal relationships may get tricky. Or maybe we centralize some logic (in particular, fighters state change), then the graph would become simple enough to use some/many/any 1:1.

I hope that with well-defined stages, new logic will find its place with ease (so, no arbitrary stages).

Regarding the performance, I think that if there is concern, we should assess it as some point - I think that given the nature of the game, we'll never need to consider performance, but it's my speculation (especially because I don't know what the low threshold :laughing:).

**Comment by 64kramsystem** [comment]
For the curious, the commands flushing topic in future Bevy versions, is described [here](https://github.com/bevyengine/rfcs/blob/2833d6bdb1386cef45c5617707be7947c25a3d68/rfcs/45-stageless.md#command-processing), and more in general, in the [whole document](https://github.com/bevyengine/rfcs/blob/2833d6bdb1386cef45c5617707be7947c25a3d68/rfcs/45-stageless.md).

**Comment by 64kramsystem** [comment]
After my reading of the future Bevy scheduler, there are my thoughs. 

First. Good news! Based on my understanding, transitioning from a multi-stage design to the new scheduler is going to be straightforward. I don't imply it will be necessarily easy, but the crucial aspect is that the concepts will map; as far as I understand, instead of stages, we'll have system sets, and they will be chained, with commands flushing (`apply_buffers`) in between each set.

Second, a general consideration. If wanted to dump the system groups concept (that is, stages as defined in this PR, or sets as in the future), I think that establishing dependencies via before/after will not realistically work.
In order for that to work (ie. not introducing subtle bugs), programmers would need to keep all the systems _and_ their query/commands in mind, and mentally view their graph; this is cognitively unapproachable, especially when the systems reach a high numer (this is not specific to Bevy, but to ECSs in general).

If we wanted to avoid the "adhoc stage" problem mentioned above, we'll probably be able to intersperse groups with individual systems, however, that will lead to the classic problem of mixed abstractions. But this is a pretty much cosmetic, secondary. problem.

**Comment by zicklag** [comment]
All that sounds like it makes sense to me. :+1:

**Comment by 64kramsystem** [comment]
I'm going to move this, and the related PR, out of the current milestone. Unfortunately, wrestling with Bevy has been taking too many hours in the last few days, and I hadn't the time to do anything concrete.

I think designing flushing is very high priority, as subtle bugs will only increase without it (I do recognize at least one hard bug, and at least another unintended side effect), however, I'll try to do something concrete, with the codebase as is now.

**Comment by 64kramsystem** [comment]
I've changed title and description of this issue to state the problem, rather than the problem _and_ the proposed solution. I've also moved the previous description to the PR, since it's still valuable information.

Can be picked up by anybody, as it's not tied anymore to a specific implementation.

**Comment by odecay** [comment]
I think we should close this for now, I don't know that its very clear or actionable any more.
